class RacesData {
    getData() {
        var data = [{
            "Core": 1,
            "Name": "Dwarf",
            "Description": "Dwarves are a short, stocky race; both male and female Dwarves stand around four feet tall and typically weigh around 120 pounds. Their long hair and thick beards are dark brown, gray or black. They take great pride in their beards, sometimes braiding or forking them. They have a fair to ruddy complexion. Dwarves have stout frames and a strong, muscular build. They are rugged and resilient, with the capacity to endure great hardships. Dwarves are typically practical, stubborn and courageous. They can also be introspective, suspicious and possessive. They have a lifespan of three to four centuries.",
            "Restrictions": "Dwarves may become Clerics, Fighters, or Thieves. They are required to have a minimum Constitution of 9. Due to their generally dour dispositions, they may not have a Charisma higher than 17. They may not employ Large weapons more than four feet in length (specifically, two-handed swords, polearms, and longbows).",
            "SpecialAbilities": "All Dwarves have Darkvision with a 60' range, and are able to detect slanting passages, traps, shifting walls and new construction on a roll of 1-2 on 1d6; a search must be performed before this roll may be made.",
            "ThiefAbilityAdjustments": "",
            "SavingThrows": "Dwarves save at +4 vs. Death Ray or Poison, Magic Wands, Paralysis or Petrify, and Spells, and at +3 vs. Dragon Breath.",
            "InitialLevels": ""
        }, {
            "Core": 1,
            "Name": "Elf",
            "Description": "Elves are a slender race, with both genders standing around five feet tall and weighing around 130 pounds. Most have dark hair, with little or no body or facial hair. Their skin is pale, and they have pointed ears and delicate features. Elves are lithe and graceful. They have keen eyesight and hearing. Elves are typically inquisitive, passionate, self-assured, and sometimes haughty. Their typical lifespan is a dozen centuries or more.",
            "Restrictions": "Elves may become Clerics, Fighters, Magic-Users or Thieves; they are also allowed to combine the classes of Fighter and Magic-User, and of Magic-User and Thief (see Combination Classes, below). They are required to have a minimum Intelligence of 9. Due to their generally delicate nature, they may not have a Constitution higher than 17. Elves never roll larger than six-sided dice (d6) for hit points.",
            "SpecialAbilities": "All Elves have Darkvision with a 60' range. They are able to find secret doors more often than normal (1-2 on 1d6 rather than the usual 1 on 1d6). An Elf is so observant that one has a 1 on 1d6 chance to find a secret door with a cursory look. Elves are immune to the paralyzing attack of ghouls. Also, they are less likely to be surprised in combat, reducing the chance of surprise by 1 in 1d6.",
            "ThiefAbilityAdjustments": "",
            "SavingThrows": "Elves save at +1 vs. Paralysis or Petrify, and +2 vs. Magic Wands and Spells.",
            "InitialLevels": ""
        }, {
            "Core": 1,
            "Name": "Halfling",
            "Description": "Halflings are small, slightly stocky folk who stand around three feet tall and weigh about 60 pounds. They have curly brown hair on their heads and feet, but rarely have facial hair. They are usually fair skinned, often with ruddy cheeks. Halflings are remarkably rugged for their small size. They are dexterous and nimble, capable of moving quietly and remaining very still. They usually go barefoot. Halflings are typically outgoing, unassuming and good-natured. They live about a hundred years.",
            "Restrictions": "Halflings may become Clerics, Fighters or Thieves. They are required to have a minimum Dexterity of 9. Due to their small stature, they may not have a Strength higher than 17. Halflings never roll larger than six-sided dice (d6) for hit points regardless of class. Halflings may not use Large weapons, and must wield Medium weapons with both hands.",
            "SpecialAbilities": "Halflings are unusually accurate with all sorts of ranged weapons, gaining a +1 attack bonus when employing them. When attacked in melee by creatures larger than man-sized, Halflings gain a +2 bonus to their Armor Class. Halflings are quick-witted, thus adding +1 to Initiative die rolls. Outdoors in their preferred forest terrain, they are able to hide very effectively; so long as they remain still there is only a 10% chance they will be detected. Even indoors, in dungeons or in non-preferred terrain they are able to hide such that there is only a 30% chance of detection. Note that a Halfling Thief will roll only once, using either the Thief ability or the Halfling ability, whichever is better.",
            "ThiefAbilityAdjustments": "",
            "SavingThrows": "Halflings save at +4 vs. Death Ray or Poison, Magic Wands, Paralysis or Petrify, and Spells, and at +3 vs. Dragon Breath.",
            "InitialLevels": ""
        }, {
            "Core": 1,
            "Name": "Human",
            "Description": "Humans come in a broad variety of shapes and sizes; the Game Master must decide what sorts of Humans live in the game world. An average Human male in good health stands around six feet tall and weighs about 175 pounds. Most Humans live around 75 years.",
            "Restrictions": "Humans may be any single class. They have no minimum or maximum ability score requirements.",
            "SpecialAbilities": "Humans learn unusually quickly, gaining a bonus of 10% to all experience points earned.",
            "ThiefAbilityAdjustments": "",
            "SavingThrows": "Humans are the “standard,” and thus have no saving throw bonuses.",
            "InitialLevels": ""
        }, {
            "Core": 0,
            "Name": "Gnome",
            "Description": "Gnomes are small and stocky, more so than Halflings but not as much as Dwarves; both male and female Gnomes stand around three and a half feet tall and typically weigh around 90 pounds. Their hair and beards may be blond, brown, black, or sometimes red. They have a fair to ruddy complexion. The most noticeable features about a Gnome from the standpoint of other races is their pointed ears and noses. They are renowned for their rapidly changing moods, sometimes gruff and contrary, sometimes whimsical and humorous. They have a lifespan between two and three centuries long.",
            "Restrictions": "Gnomes may become Clerics, Fighters, Magic-Users, Thieves, or Magic-User/Thieves. They are required to have a minimum Constitution of 9. Due to their small stature, they may not have a Strength higher than 17. Gnomes never roll larger than six-sided dice (d6) for hit points regardless of class. They may not employ Large weapons more than four feet in length (specifically, two-handed swords, polearms, and longbows). With respect to encumbrance, treat Gnomes as equivalent to Halflings.",
            "SpecialAbilities": "All Gnomes have Darkvision with a 30' range. When attacked in melee by creatures larger than man-sized, Gnomes gain a +1 bonus to their Armor Class. Gnomes are naturally very observant; being smaller than most other races has made them cautious and aware of their surroundings. As a consequence, a gnome has a 10% chance to detect an invisible or hidden creature within a 30' radius. This ability does not apply to inanimate objects such as secret doors or invisible objects. A thief hiding in shadows, an invisible sprite, or a character wearing an elven cloak may all be detected in this way. As with any detection ability, the GM should make this roll. A gnome who has detected a hidden thief can see him or her dimly; truly invisible creatures are sensed by their breathing, by the way echoes change in their vicinity, and so on. When fighting an invisible opponent, a gnome who has successfully detected the invisible creature suffers only a -2 penalty on the attack roll, rather than the usual -4 penalty as given on page 52 of the Core Rules.",
            "ThiefAbilityAdjustments": "",
            "SavingThrows": "Gnomes save at +4 vs. Death Ray or Poison, and at +3 vs. Dragon Breath.",
            "InitialLevels": ""
        }, {
            "Core": 0,
            "Name": "Half-elf",
            "Description": "Half-Elves are the result of crossbreeding between Elves and Humans. An average Half-Elf male stands around 5'5” in height, with females averaging an inch shorter. They have pointed ears, but their features tend to favor the Human parent a bit more than the Elf. Half-Elves are well tolerated by Humans in most cases, but are often shunned (or at best, ignored) by Elven society.",
            "Restrictions": "Half-Elves may become members of any class or combination allowed to Elves. They are required to have a minimum Intelligence of 9, and like Elves they may not have Constitution scores higher than 17. They do not suffer from the Elven hit dice limit.",
            "SpecialAbilities": "Half-Elves have Darkvision with a 30' range. They are able to find secret doors on a 1-2 on 1d6, but do not find secret doors on a cursory examination as Elves do. Half-Elves gain a bonus of +5% on all earned experience, except if the Half-Elf is a member of a combination class.",
            "ThiefAbilityAdjustments": "",
            "SavingThrows": "Half-Elves save at +1 vs. Magic Wands and Spells.",
            "InitialLevels": ""
        }, {
            "Core": 0,
            "Name": "Half-Ogre",
            "Description": "Half-Ogres are the result of crossbreeding between Humans and Ogres. Such creatures tend to be outcasts within both Human and Ogrish communities, but they may often be found as leaders in communities of orcs or goblins. Half-Ogres are big, averaging around 7' in height, broad shouldered and rangy. Their features tend to favor the Ogrish parent, with dark coarse hair, tan or brown skin and dark eyes.",
            "Restrictions": "Half-Ogres may become Clerics or Fighters only. A Half-Ogre must have a minimum of 13 in both Strength and Constitution, and may not have either Intelligence or Wisdom higher than 15.",
            "SpecialAbilities": "Half-Ogres roll hit dice one size larger than normal; so a Half-Ogre Fighter rolls d10's for hit points, while a Half-Ogre Cleric rolls d8's. Half-Ogres gain a bonus of +5% on all earned experience. Due to their great size, they gain a bonus of +1 on the roll when opening doors or performing other feats of Strength. Finally, they have Darkvision with a 30' range.",
            "ThiefAbilityAdjustments": "",
            "SavingThrows": "Half-Ogres gain no special bonuses to their saving throw rolls.",
            "InitialLevels": ""
        }, {
            "Core": 0,
            "Name": "Half-Orc",
            "Description": "Half-Orcs are the result of crossbreeding between Humans and Orcs. Such creatures tend to be outcasts within Human communities, but sometimes rise to positions of leadership within Orcish communities. Half-Orcs are a bit shorter than Humans. Their features tend to favor the Orcish parent.",
            "Restrictions": "Half-Orcs may become members of any class. A Half-Orc must have a minimum Constitution of 9, and are limited to a maximum Intelligence of 17.",
            "SpecialAbilities": "Half-Orcs gain a bonus of +5% on all earned experience. They have Darkvision with a 60' range. When dealing with humanoids of Human-size or smaller, a Half-Orc gains an additional +1 on any reaction die roll, in addition to his or her Charisma bonus.",
            "ThiefAbilityAdjustments": "",
            "SavingThrows": "Half-Orcs save at +1 vs. Death Ray or Poison.",
            "InitialLevels": ""
        }, {
            "Core": 0,
            "Name": "Bugbear",
            "Description": "Bugbears look like huge, hairy goblins, standing about 6 feet tall. Their eyes are usually a darkish brown color and they move very quietly. They are wild and relatively fearless, and bully smaller humanoids whenever possible.",
            "Restrictions": "A bugbear may become a Fighter, Cleric, or Thief. Bugbear Clerics are called Shamans. When permitted by the GM, bugbears may be allowed to advance in certain optional classes. Likewise, a GM may exclude certain choices. A bugbear character must have minimum Strength score of 13 and Dexterity score of 9. Bugbears are limited to a maximum of 15 in both Intelligence and Charisma.",
            "SpecialAbilities": "Bugbears prefer to ambush opponents if they can. When hunting, they often send scouts ahead of the main group. Bugbear attacks are coordinated, and their tactics are sound if not brilliant. They are able to move in nearly complete silence, surprising opponents on 1-3 on 1d6. Like most dark dwelling races, a bugbear has Darkvision out to 60’.",
            "ThiefAbilityAdjustments": "A bugbear Thief has a +20% bonus to Move Silently and despite its size gets a bonus of +10% on Hide checks.",
            "SavingThrows": "A bugbear gains no special bonus to its saving throw rolls.",
            "InitialLevels": "A bugbear character begins play at negative 3,000 experience points with 1d8 for hit points and an attack bonus of +1, but it does not have any stealth bonus (not learned yet). When it achieves -1,500 experience points it gets another 1d8 hit points and another point of attack bonus (+2 total). While in this immature state it can only utilize leather armor and saves as a 1st-level Fighter. Upon achieving zero experience points, it must choose its career path (class) as a 1st-level character and begins to abide by various class-based restrictions. It rolls using its new class-based hit die but retain previous hit points and attack bonuses (+2 bonus is added to attack bonus). At this point it has learned to be stealthy as well. When subjected to spells or effects where level or hit dice is a consideration, add two to its effective level. Thus, a bugbear with its first class level has 2d8 hit points and +2 attack bonus in addition to that granted by its chosen class. It is equivalent to a 3rd-level character."
        }, {
            "Core": 0,
            "Name": "Caveman",
            "Description": "Cavemen are a species closely related to Humans; they are shorter and stockier, and much more heavily muscled. They do not all actually live in caves. Whether they are actually less intelligent than “normal” humans or not is a matter of debate, but it is true that they do not have the facility for language that other human, demi-human, and humanoid races have. However, they do seem to be able to communicate basic information amongst themselves through complex grunts and vocalizations similar to what one might hear from the great apes.",
            "Restrictions": "A caveman may become a Fighter, Cleric, or Thief. Caveman Clerics are called Shamans by other races, although such spell casters vocalize their spells in peculiar ways that are unrecognizable by other races. Cavemen are wise in the ways of nature, and when permitted by the GM cavemen may be allowed to advance in certain optional classes, especially those associated with nature. Likewise, a GM may exclude certain choices. A caveman character must have a minimum Strength score of 13, and scores of 9 in both Dexterity and Constitution. Cavemen are limited to a maximum of 15 in both Intelligence and Charisma, generally accounting to their lack of ability to communicate or understand advanced concepts. A Caveman can ‘learn’ languages, but only rudimentary concepts are understood. In any case they cannot verbalize normal languages of other humanoids.",
            "SpecialAbilities": "Cavemen are very attuned to their surroundings, and like Elves are seldom surprised, reducing the die roll range for surprise by 1 point. Therefore in normal situations, a caveman is surprised only on a roll of 1 on d6.",
            "ThiefAbilityAdjustments": "A caveman Thief has a +20% bonus to Climb and +10% when Hiding or Moving Silently. It suffers -10% penalties with Open Locks or Find/Remove Traps. A caveman with Tracking skills has a +10% bonus.",
            "SavingThrows": "Cavemen gain no special bonuses to saving throw rolls.",
            "InitialLevels": "A Caveman begins play at negative 1,500 experience points with 1d8 for hit points and an attack bonus of +1. While in this immature state it can only utilize leather armor and makes saves as a 1st-level Fighter. Upon achieving zero experience points it must choose a career path (class) as a 1st-level character and begins to abide by various class-based restrictions. It rolls using this new class-based hit die but retain previous hit points and attack bonuses (+1 bonus is added to attack bonus). When subjected to spells or effects where level or hit dice is a consideration, add one to its effective level. Thus, a caveman at first class level has 1d8 hit points and +1 attack bonus in addition to that granted by its chosen class. It is equivalent to a 2nd-level character."
        }, {
            "Core": 0,
            "Name": "Centaur",
            "Description": "Centaurs appear to be half man, half horse, having the torso, arms, and head of a man in the position a horse's head would normally occupy. A centaur is as big as a heavy horse, but much taller and slightly heavier; average males are about 7’ tall and weigh about 2,100 pounds, and females are just a bit smaller. Centaurs may charge with a spear or lance just as a man on horseback, with the same bonuses. Centaurs are generally haughty and aloof, but very honorable. Most would rather die than allow humans, demi-humans, or humanoids to ride on their backs.",
            "Restrictions": "A centaur may become a Fighter, Cleric, or rarely Magic-User. Centaurs prefer professions associated with nature or the outdoors, and when permitted by the GM centaurs may be allowed to advance in certain optional classes. Likewise, a GM may exclude certain choices. A centaur character must have minimum Strength and Constitution scores of 11 (which represents the human portion of their physique), and a Wisdom score of 9. A centaur's Dexterity and Charisma is limited to a maximum of 16. A centaur may not wear standard armor, only custom built, costing three or more times the normal purchase price. Likewise, normal footwear is unusable. A centaur in combat is treated as Large (for instance against Halflings) and one has to deal with a Turning Radius of 10’.",
            "SpecialAbilities": "Due to its great mass, a classed centaur rolls hit dice one size larger than normal; a d4 would become a d6, a d6 to d8, etc. A centaur is never truly unarmed, as it can attack with its 2 front hooves for 1d6 points of damage each in addition to a weapon strike. A centaur often charges into battle (+2 to hit with double damage, following all normal charging rules) and when using a spear or lance is treated like a mounted person. A centaur must forgo all its attacks in order to cast spells. He gets an additional +1 bonus on feats of strength such as opening doors due to its great size. A centaur's base movement rate is 60' when lightly encumbered and 40' under heavier loads. A light load for a centaur is up to 250 pounds; a heavy load is up to 500 pounds, but a centaur is not accustomed to load bearing like similarly-sized true horses.",
            "ThiefAbilityAdjustments": "There are no roguish centaurs, but if using non-standard class options one may have one or more typical Thief abilities, having a -20% penalty to Pick Pockets, Move Silently, and Hide. Climbing sheer walls is effectively impossible without block and tackle equipment, but when it comes to narrow ledges, steep inclines, or other “near climbing” situations the penalty is -40%.",
            "SavingThrows": "A centaur gains no special bonuses to its saving throw roll. However, because of racial hit dice a centaur has a +1 bonus to all saves.",
            "InitialLevels": "A centaur begins play at negative 4,500 experience points with 1d8 for hit points and an attack bonus of +1, but it does not have any hoof attack. When it reaches negative 3,000 experience points it gets another 1d8 hit points, another +1 attack bonus, and may make one hoof strike per round (in addition to any weapon). When it reaches -1,500 experience points it gets a third 1d8 in hit points and its racial save bonus of +1 (from hit dice), but it does not get another attack bonus at this time. While in this immature state, it may not wear armor, rolls saves as a 1st-level Fighter (note the previously mentioned bonus). Upon achieving 0 experience points, it must choose its career path (class) as a 1st-level character and begins to abide by various class-based restrictions. At this point it has full attack routines (2 hooves + weapon). When subjected to spells or effects where level or hit dice is a consideration, add three to its effective level. Thus, a centaur with its first class level has 3d8 hit points and +2 attack bonus in addition to that granted by its chosen class. It is equivalent to a 4th-level character."
        }, {
            "Core": 0,
            "Name": "Gnoll",
            "Description": "Gnolls are hyena-headed, evil humanoids that wander in loose tribes. Most gnolls have dirty yellow or reddish-brown fur. An adult male gnoll is about 7’ feet tall and weighs 300 pounds. Gnolls are nocturnal carnivores, preferring intelligent creatures for food because they scream more. Gnoll Fighters are the most common, but they show little discipline when fighting unless they have a strong leader. Gnoll Clerics are called Shamans and often prefer to utilize reversed (evil) versions of spells. Likewise, gnoll Magic-Users are generally called Warlocks or Witches (often preferring optional “evil-oriented” subclasses when allowed by the GM). Rarely one may come across a gnoll Cleric/Magic-User called a Witch-Doctor.",
            "Restrictions": "A gnoll character may become a Fighter, Cleric, or occasionally a Magic-user. When permitted by the GM, certain optional subclasses are especially appropriate for gnolls. Likewise, a GM may exclude certain class choices as inappropriate. A gnoll character must have a minimum Strength score of 13 and Constitution score of 11. Gnolls are savage, brutish, and cruel, and are limited to scores of 15 in both Intelligence and Charisma.",
            "SpecialAbilities": "In its role as a scavenger, a gnoll is especially attuned to scent. A gnoll is able to identify individuals by scent alone. This powerful olfactory sense allows it to determine the presence of concealed or invisible creatures, and any penalties associated with combating such foes is halved. For instance, a gnoll suffers only a -2 penalty when attacking an invisible pixie. Like most dark-dwelling races, gnolls have Darkvision out to 60’.",
            "ThiefAbilityAdjustments": "Gnolls do not become standard Thieves, but if using non-standard class options a gnoll may have one or more typical Thief abilities. Such gnolls have a bonus of +10% on Hear Noise attempts. A gnoll with the Tracking ability has a +10% bonus on that skill due primarily from its keen sense of smell.",
            "SavingThrows": "As a scavenger and carrion eater, a gnoll is especially hearty against many deadly effects. A gnoll character has saving throw bonuses of +4 vs. Death Ray, Poison, Paralysis, or Petrification.",
            "InitialLevels": "A gnoll begins play at negative 1,500 experience points, 1d8 for hit points, and an attack bonus of +1. While in this immature state it can only utilize leather armor and saves as a 1st-level Fighter. Upon achieving 0 experience points, it must choose its career path (class) as a 1st-Level character and begin to abide by various class-based restrictions. It rolls using its new class-based hit die but retains previous hit points and attack bonuses (+1 bonus is added to attack bonus). When subjected to spells or effects where level or hit dice is a consideration, add one to its effective level. Thus, a gnoll with its first class level has 1d8 hit points and +1 attack bonus in addition to that granted by its chosen class. It is equivalent to a 2nd-level character."
        }, {
            "Core": 0,
            "Name": "Goblin",
            "Description": "Goblins are small, wicked humanoids that favor ambushes, overwhelming odds, dirty tricks, and any other edge they can devise. An adult goblin stands around 3’ tall and weighs around 40 pounds. Its eyes are usually bright and crafty-looking, varying in color from red to yellow. A goblin’s skin color ranges from yellow through any shade of orange to a deep red; usually all members of a single tribe are about the same color. Goblins wear clothing of dark leather, tending toward drab, soiled-looking colors.",
            "Restrictions": "A goblin may become any of the standard classes. Goblin Clerics are called Shamans, and on occasion one may encounter a Goblin Witch-Doctor, which is simply a Cleric/Magic-User combination class. When permitted by the GM a goblin may be allowed to advance in certain optional classes. Likewise, a GM may exclude certain choices. A goblin character must have a minimum Dexterity score of 9. Goblins do not have great fortitude, and are limited to maximum scores of 16 in Strength and Constitution. In addition to the Constitution limitation, goblins must subtract one point from every hit die roll, down to a minimum of 1 hit point per die. However, a goblin with a class hit die less than d6 does not apply the -1 deduction to hit point rolls (Constitution bonus/penalty still applies). A goblin may not use Large weapons, and must wield Medium weapons with both hands. Likewise a goblin must utilize smaller-sized armor.",
            "SpecialAbilities": "Like Halflings, a goblin gains a +2 bonus to its armor class when attacked in melee by creatures larger than man-sized. Crafty and mechanically inclined, a goblin notices secret doors as well as an Elf (1-2 on 1d6 rather than the usual 1 on 1d6). Likewise, one is so observant that it has a 1 in 1d6 chance to find a secret door with just a cursory look. Like Dwarves, a goblin is able to detect slanting passages, traps, shifting walls, and new construction on a roll of 1-2 on 1d6; a search must be performed before this roll may be made. Like most dark-dwelling races, a Goblin has Darkvision out to 60’.",
            "ThiefAbilityAdjustments": "A goblin Thief has a +10% bonus to Open Locks and Finding/Removing Traps.",
            "SavingThrows": "A goblin character gains no special bonuses to saving throw rolls.",
            "InitialLevels": ""
        }, {
            "Core": 0,
            "Name": "Hobgoblin",
            "Description": "Hobgoblins are larger cousins of goblins, being about the same size as humans. Its hair color ranges from dark reddish-brown to dark gray. It has dark orange or red-orange skin. Large males have blue or red noses. A hobgoblins' eyes are yellowish or dark brown, while its teeth are yellow. Its garments tend to be brightly colored, often blood red with black-tinted leather. Its weaponry is kept polished and in good repair. Hobgoblins are cruel and calculating warriors, always looking to exploit those weaker than themselves. They have a strong grasp of strategy and tactics and are capable of carrying out sophisticated battle plans. Under the leadership of a skilled strategist or tactician, their discipline can prove a deciding factor. Hobgoblins hate Elves and attack them first in preference over other opponents. Hobgoblin deities reinforce this militaristic outlook, and their Clerics often have access to one or more weapons outside of the normal clerical choices such as a sword or spear.",
            "Restrictions": "A hobgoblin character may become any of the standard character classes. Hobgoblin Clerics are called Shamans, and on occasion one may encounter a Hobgoblin Witch-Doctor which is simply a Cleric/Magic-User combination class. When permitted by the GM a hobgoblin may be allowed to advance in certain optional classes. Likewise, a GM may exclude certain choices. A hobgoblin character must have minimum Strength and Charisma score of 9.",
            "SpecialAbilities": "Militaristic and always on alert, a Hobgoblin character is seldom surprised. Like Elves, it is surprised only on a roll of 1 on 1d6 (one point better). Even against well-planned ambushes, surprise is only achieved against a hobgoblin on a roll of 1-3 on 1d6. While not as mechanically-minded as normal goblins, a hobgoblin is still very alert, noticing secret doors as well as an Elf (1-2 on 1d6 rather than the usual 1 on 1d6). Likewise, a hobgoblin is so observant that it has a 1 in 1d6 chance to find a secret door with just a cursory look. Like most dark-dwelling races, a hobgoblin has Darkvision out to 60’.",
            "ThiefAbilityAdjustments": "Given their “always alert” status, a roguish hobgoblin has a +5% bonus to Listen and Finding/Removing Traps.",
            "SavingThrows": "A hobgoblin character gains no special bonuses to its saving throw rolls.",
            "InitialLevels": ""
        }, {
            "Core": 0,
            "Name": "Kobold",
            "Description": "Kobolds are small, dog-faced reptilian humanoids. A kobold is 2’ tall and weighs about 40 pounds. Kobolds tend to perceive larger races as enemies, and are naturally distrustful when encountered. Regardless, kobolds are cunning foes. It prefers ranged combat, closing only when it can see that its foes have been weakened. Whenever it can, a kobold sets up ambushes near trapped areas.",
            "Restrictions": "A kobold character may become any of the standard character classes. When permitted by the GM a kobold may be allowed to advance in certain optional classes. Likewise, a GM may exclude certain choices. A kobold character must have a minimum Dexterity score of 11 and is limited to a maximum score of 15 in Strength. Also size related, a kobold rolls hit dice one size smaller than normal; a d8 would become a d6, a d6 to d4, and a d4 would instead be d3. A kobold may not use Large weapons, and must wield Medium weapons with both hands. Likewise a kobold must utilize smaller-sized armor. The tunneling kobolds dwell almost entirely within dark environs, and one will suffer a -1 penalty to attack rolls in bright sunlight or within the radius of light spells.",
            "SpecialAbilities": "Like Halflings, a kobold gains a +2 bonus to its armor class when attacked in melee by creatures larger than man-sized. Another similarity to Halflings, a kobold also has a +1 attack bonus when using ranged weapons. Kobolds are masters of trap-works and are otherwise very mechanically inclined. A kobold character notices secret doors as well as an Elf (1-2 in 1d6 rather than the usual 1 in 1d6). Likewise, a kobold is so observant that it has a 1 in 1d6 chance to find a secret door with just a cursory look. Kobolds are masterful miners, and like Dwarves, a kobold is able to detect slanting passages, traps, shifting walls, and new construction on a roll of 1-2 on 1d6; a search must be performed before this roll may be made. A kobold has Darkvision out to 90’.",
            "ThiefAbilityAdjustments": "Kobolds are considered to be masters at trap-works; a roguish kobold has a +15% bonus to Finding/Removing Traps. In addition, it has +5% bonuses to Open Locks, Move Silently, and Hiding.",
            "SavingThrows": "A kobold saves at +4 against poison effects, a result of extensive exposure to various poisons in its environment while growing up.",
            "InitialLevels": ""
        }, {
            "Core": 0,
            "Name": "Lizard Man",
            "Description": "A lizard man is usually 6’ to 7’ tall with green, gray, or brown scales. Its tail is used for balance and is 3’ to 4’ long. Adult males can weigh from 200 to 250 pounds and are always very strong. Lizard men are largely indifferent to other races, being primarily interested in their own survival. If aroused, however, they are fearsome warriors, using simple but sound tactics.",
            "Restrictions": "A lizard man may become a Fighter or Cleric. Lizard men generally prefer professions associated with nature or survival. When permitted by the GM a lizard man may be allowed to advance in certain optional classes. Likewise, a GM may exclude certain choices. A lizard man character must have a minimum Strength score of 13. Lizard men have trouble relating to most other races and are limited to a maximum score of 15 in Charisma.",
            "SpecialAbilities": "Lizard men are excellent swimmers and can hold their breath for an extended period of time (up to a full turn). One cannot swim while wearing armor; however, a lizard man often hides in the water even while armored, standing on the bottom with just nose and eyes exposed (similar to a crocodile). When it is able to employ this maneuver, a lizard man surprises on 1-4 on 1d6. A lizard man's scaly hide provides it with a +1 bonus to armor class, but otherwise only specially-made armors can be worn (often costing 3 or more times the normal price). A lizard man can bite for 1d4 points of damage, but it must forgo any weapon attacks that round. Upon a successful bite attack the lizard man may hold on, causing 1 point of damage each round (requiring the opponent to make a Strength check to break the hold). This is often done in or near water in order to drown a victim.",
            "ThiefAbilityAdjustments": "Lizard men cannot become Thieves, but if non-standard class options are utilized, a lizard man has -10% penalty on Open Locks, Remove Traps, or Picking Pockets.",
            "SavingThrows": "A lizard man gains no special bonuses to its saving throw rolls.",
            "InitialLevels": "A lizard man begins play at negative 1,500 experience points, uses 1d8 for hit points, and has a +1 attack bonus. While in this immature state it can only utilize leather armor (if available) and saves as a 1st-level Fighter. Upon achieving 0 experience points, it must choose its career path (class) as a 1st-Level character and must abide by any class-based restrictions. It rolls using its new class-based hit die but retains its previous hit points and attack bonuses (+1 bonus is added to attack bonus). When subjected to spells or effects where level or hit dice is a consideration, add one to its effective level. Thus, a lizard man in its first class level has 1d8 hit points and +1 attack bonus in addition to those granted by the chosen class. It is equivalent to a 2nd-level character."
        }, {
            "Core": 0,
            "Name": "Ogre",
            "Description": "Ogres appear as large, very ugly humans. Adult ogres stand 9’ to 10’ tall and weigh 600 to 650 pounds. Its skin color ranges from dull yellow to dull brown. Its clothing consists of poorly-cured furs and hides, which add to its naturally-repellent odor. Ogres are brutish and aggressive, but inherently lazy.",
            "Restrictions": "An ogre may become a Fighter or rarely a Cleric. Ogres usually lack the sophistication for other options, but certain optional subclasses might be allowed by the GM. Likewise, a GM may exclude certain class choices as inappropriate. An ogre character must have a minimum Strength score of 15 and Constitution score of 13. An ogre is generally deficient in its intellect and ability to interact with others; it is limited to a score of 13 for both Intelligence and Charisma. Likewise, an ogre is not wise nor particularly dexterous, and it is limited to a score of 15 in both Wisdom and Dexterity. An ogre in combat counts as a Large opponent (for instance against Halflings), and only specially-made large armors can be worn (often costing 3 or more times the normal price).",
            "SpecialAbilities": "Due to its great mass, a properly classed ogre rolls hit dice one size larger than normal; a d4 would become a d6, a d6 to d8, etc. An ogre is never truly unarmed, as it can attack with its fists for 1d8 subduing points of damage per hit. An ogre character rolls attacks normally with most weapons, applying its Strength bonus to damage. However, when properly equipped with tremendously over-sized weapons (often crudely constructed), an ogre may forgo its normal damage bonus from strength and instead roll 2d6 for damage. An ogre gets an additional +1 bonus on feats of strength such as opening doors due to its great size. Like many humanoid races, an ogre has Darkvision out to 60.",
            "ThiefAbilityAdjustments": "Ogres cannot become Thieves, but if non-standard class options are utilized, an Ogre has -20% penalty on Open Locks, Remove Traps or Picking Pockets. Likewise, stealth is difficult; an ogre has a -10% penalty to Move Silently and Hide. However, it can Climb readily, getting a +10% bonus, assuming what it is climbing is stable with the addition of the ogre's weight.",
            "SavingThrows": "An ogre gains no special bonuses to its saving throw roll. However, because of the racial hit dice it has a +1 bonus to all saves.",
            "InitialLevels": "An ogre begins play at negative 4,500 experience points, uses 1d8 for hit points, and has an attack bonus of +1, but its fist attack deals only 1d4 subduing points of damage. When it reaches -3,000 experience points it gets another 1d8 hit points, another +1 attack bonus, and its fist attacks deal 1d6 subduing points of damage. When it reaches -1,500 experience points it gets a third 1d8 in hit points and its racial save bonus of +1, but the ogre does not get another attack bonus at this time. While in this immature state, it may only wear leather armor (if available), and rolls saves as a 1st-level Fighter (note the previously mentioned bonus). Upon achieving 0 experience points, it must choose its career path (class) as a 1st-level character and begin to abide by various class based restrictions. At this point it has full attack potential. When subjected to spells or effects where level or hit dice is a consideration, add three to the ogre's effective level. Thus, an ogre at its first class level has 3d8 hit points and +2 attack bonus in addition to that granted by its chosen class. It is equivalent to a 4th-level character."
        }, {
            "Core": 0,
            "Name": "Orc",
            "Description": "Orcs are grotesque humanoids bent on war and domination. It has lupine ears, reddish eyes, truncated, upturned noses, and black hair (but very little body hair). An adult male orc is a little over 6’ tall and weighs about 210 pounds; females are slightly smaller. An orc prefers to wear vivid colors that many humans would consider unpleasant, such as blood red, mustard yellow, yellow-green, and deep purple. It utilizes all manner of weapons and armor scavenged from battlefields. It speaks its own rough and simple language, but many also speak some Common or Goblin.",
            "Restrictions": "An orc may become a Cleric, Fighter, or Thief. Orc Clerics are called Shamans. When permitted by the GM an orc may be allowed to advance in certain optional classes. Likewise, a GM may exclude certain class choices. An orc character must have a minimum Strength and Constitution score of 9. An orc is limited to a maximum score of 15 in both Intelligence and Charisma. Orcs prefer dark environs such as underground, deep ravines, or dark forested areas, and it suffers a -1 penalty to attack rolls in bright sunlight or within the radius of light spells.",
            "SpecialAbilities": "Like most dark-dwelling races, orcs have Darkvision out to 60’, but suffer penalties in bright light (see above).",
            "ThiefAbilityAdjustments": "An orc Thief has a +10% bonus to Climb Walls and Listen.",
            "SavingThrows": "An orc character has a +2 bonus on saves vs. Death Ray and Poison.",
            "InitialLevels": ""
        }, {
            "Core": 0,
            "Name": "Troglodyte",
            "Description": "Troglodytes are very intelligent lizard-like humanoid creatures. It has large red eyes and spiny 'combs' on its legs, head, and arms. It normally stands 5’ to 6’ tall. In general troglodytes are very hostile, attacking equal or weaker non-troglodyte groups on sight. It prefers to attack with surprise, depending on its color-changing ability for this (see below).",
            "Restrictions": "A troglodyte may become a Fighter, Cleric, or Thief. When permitted by the GM a troglodyte may be allowed to advance in certain optional classes. Likewise, a GM may exclude certain choices. A troglodyte character must have a minimum Intelligence and Constitution score of 11. Troglodyte mentality is often quite alien to most other races, and they are limited to maximum scores of 15 in both Wisdom and Charisma.",
            "SpecialAbilities": "A troglodyte can change color at-will, and 50% of the time it can blend into the environment well enough to surprise on a roll of 1-5 on 1d6. Furthermore, it gains a +2 attack bonus during any surprise round due to its excellent ambush skills. Note that a troglodyte Thief will roll for hiding attempts only once, using either the Thief ability or the troglodyte ability, whichever is better. A troglodyte secretes an oily smelly substance that keeps its scaly skin supple. All mammals (including most character races) find the scent repulsive, and those within 10’ of the troglodyte must make a save vs. Poison. Those failing the save suffer a -2 penalty to attack rolls while they remain within range of the troglodyte. Getting out of range negates the penalty, but renewed exposure reinstates the penalty. The result of the original save lasts 24 hours, when a new save can be rolled. A troglodyte can attack with its two front claws doing 1d4 points of damage each, as well as a bite attack for 1d4 points of damage. A troglodyte cannot mix its natural attacks with weapon strikes; it has to choose. A troglodyte's scaly hide provides it with a +1 bonus to armor class, but otherwise only specially-made armors can be worn (often costing 3 or more times the normal price).",
            "ThiefAbilityAdjustments": "Because of its natural abilities, a troglodyte Thief has a +20% bonus to Hide attempts and +10% bonus when Moving Silently or Climbing. A troglodyte's natural hiding ability may be superior to its Thief skill, especially at lower levels.",
            "SavingThrows": "A troglodyte character gains no special bonuses to its saving throw rolls.",
            "InitialLevels": "A troglodyte begins play at negative 1,500 experience points, uses 1d8 for hit points, has an attack bonus of +1, and its natural attacks do 1d3 points of damage. While in this immature state it can only utilize leather armor (if available) and saves as a 1st-level Fighter. Upon achieving 0 experience points it must choose its career path (class) as a 1st-level character and begins to abide by any class-based restrictions. It rolls using its new class-based hit die but retains any previous hit points and attack bonuses (+1 bonus is added to its attack bonus). At this point, its natural attacks do full damage (1d4). When subjected to spells or effects where level or hit dice is a consideration, add one to its effective level. Thus, a troglodyte at its first class level has 1d8 hit points and +1 attack bonus in addition to that granted by its chosen class. It is equivalent to a 2nd-level character."
        }, {
            "Core": 0,
            "Name": "Bisren",
            "Description": "The Bisren are a race descended from the great Minotaurs of legend. Normally peaceful, Bisren enjoy nature and keep a semi-nomadic lifestyle in regions that other races call wild. When threatened, Bisren can become quite dangerous, much like their warrior ancestors. Bisren are impressively muscled and generally average 7’ tall, with some individuals reaching almost 8’ in height.",
            "Restrictions": "Bisren prefer professions associated with their nature-oriented lifestyles and may become Fighters or Clerics (often choosing Ranger or Druid if those optional classes are available). While it is rare to find a Bisren Thief, they are not barred from the class (although they do suffer several penalties to roguish abilities). A Bisren character must have minimum Strength and Constitution scores of 11. Not particularly bright or dexterous, Bisren are limited to 17 in both Dexterity and Intelligence. Bisren may wear human-sized armor, albeit often adjusted slightly to account for their size. Their cloven-hoof feet may not wear typical footwear, unless specially produced for Bisren. Specially-constructed helmets are likewise needed to fit their horned heads.",
            "SpecialAbilities": "Bisren roll hit dice one size larger than normal; a d4 would become a d6, a d6 to d8, etc. Bisren are never truly unarmed, as they can gore for 1d6 damage with their horns. Bisren often charge into battle with a gore attack (+2 to hit with double damage, following all normal charging rules) and then switch to weaponry for the remainder of the fight. They must choose whether to attack with weapons or to gore; they cannot do both in a round. Bisren get an additional +1 bonus on feats of strength such as opening doors due to their great size.",
            "ThiefAbilityAdjustments": "Roguish Bisren have a -10% penalty to Open Locks, Removing Traps, and Picking Pockets. Stealth checks (Moving Silently and Hiding) for Bisren are made normally, although in non-wilderness areas such as indoors, underground (dungeons), or in urban areas they suffer a -20% penalty to their chance to succeed. Outdoor traps, such as hunting snares or dead-falls, do not apply the above penalty and instead are made at +10% bonus.",
            "SavingThrows": "Bisren gain no special bonuses to their saving throw rolls.",
            "InitialLevels": ""
        }, {
            "Core": 0,
            "Name": "Canein",
            "Description": "A legend exists that there was a wizard who loved his dogs. This mage kept dogs as pets, trained them to guard his estate, and even used them in magical experiments to enhance their ability to serve. They were gifted with greater intelligence and a more humanoid stature. It is unknown whether the legend is entirely true or not, but it is generally assumed to be the genesis of the Caneins. Caneins are a race of dog-like humanoids, known for their extreme sense of loyalty whether to liege, friend, or family. There is a great deal of physical variance among the individual Caneins, with some short and stocky, others leanly-muscled, and variations in the colorations of their coats. However, all Caneins share a similar facial structure similar to the various bulldog or boxer-type dog breeds, having jowls and squat features. Caneins vary in their height, but are rarely larger than the average human. Caneins often form almost knight-like codes and attitudes, often serving a patron in exactly that capacity.",
            "Restrictions": "Caneins can be any class, although they seldom become Thieves. Even when a Canein Thief is found, it typically uses the skills of that profession in more honorable ways than the typical rogue. A Canein must have a minimum Constitution of 9, and is limited to a maximum Intelligence of 17.",
            "SpecialAbilities": "Caneins have a keen sense of smell, able to identify individuals by their scent alone. This power olfactory sense allows the Canein to determine the presence of concealed or invisible creatures, and any penalties associated with combating such foes is halved for the Canein. For instance, a Canein suffers only a -2 penalty when attacking an invisible pixie. All Caneins can track as a Ranger of equivalent level, and an actual Canein Ranger (if the class is allowed by the GM) gets a bonus of +20% on Tracking rolls. Caneins have +2 on any reaction rolls involving other canine creatures. However, Caneins do not like vile beasts such as werewolves, hellhounds, and the like, despite any similarities.",
            "ThiefAbilityAdjustments": "",
            "SavingThrows": "Caneins save at +2 vs. Death Ray or Poison as well as vs. Paralysis and Petrification effects.",
            "InitialLevels": ""
        }, {
            "Core": 0,
            "Name": "Chelonian",
            "Description": "Inhabiting river and lake regions, Chelonian are a race of reptilian humanoids bearing some semblance to turtles. They are normally content to remain within their own societies, but on occasion a more adventurous individual can be found. They are protected by thick scaly skin as well as a shell-like growth that covers their backside. Chelonian are seldom taller than 5’ or so.",
            "Restrictions": "Chelonian may become members of any class. A Chelonian must have a minimum Constitution score of 11, and is limited to a maximum Dexterity score of 17. Normal armors will not fit the physique of a Chelonian and they normally use only shields to enhance their defenses. Specially-constructed armors can be acquired, costing substantially more than listed prices and requiring extra time to create.",
            "SpecialAbilities": "A Chelonian's thick skin grants it a base AC of 13 (equivalent to leather armor), and a Chelonian's back is especially tough with an AC of 17 (equivalent to plate mail only for rear attacks). Use these figures unless any armor worn grants better AC, then use the armor’s AC. A shield will be still effective in either case. Chelonian swim no better than other humanoid races, but they can hold their breath twice as long. In addition, their underwater vision is also twice as good as normal.",
            "ThiefAbilityAdjustments": "",
            "SavingThrows": "Chelonian save at +2 vs. Poison.",
            "InitialLevels": ""
        }, {
            "Core": 0,
            "Name": "Faun",
            "Description": "Fauns are a fey-related race that resemble a sort of strange cross of goat with that of a small human or elf-like being. Standing only about 4’ to 5’ tall, they have a human-like torso and head, but the legs and feet of a goat. One can find Fauns with other small features reminisce of goats such as small horns or large ears. Fauns share the Halfling love of simple agrarian life, especially with respect to vineyards, as they prize wine (among other brews) above most things in life. Fauns love frivolity and are often quite adept at musical pursuits.",
            "Restrictions": "Fauns can choose any class. A Faun will typically follow the tenets of nature deities, and Clerics and Druids (if allowed by the GM) can be found equally in their societies. A Faun must have a minimum Constitution score of 9, and is limited to a maximum Charisma score of 15, generally accounted to overly gregarious personalities and lack of inhibitions. Fauns may not wear typical human-style footwear.",
            "SpecialAbilities": "Fauns have Darkvision out to 30’. They are resistant to charm-like effects from fey beings, getting a +4 bonus on relevant saves. This includes charms of dryads, nixies, and similar beings (GM’s decision when necessary).",
            "ThiefAbilityAdjustments": "",
            "SavingThrows": "Like Dwarves, Fauns save at +4 vs. Death Ray or Poison, Magic Wands, Paralysis or Petrify, and Spells, and at +3 vs. Dragon Breath.",
            "InitialLevels": ""
        }, {
            "Core": 0,
            "Name": "Phaerim",
            "Description": "The beautiful Phaerim are related to fey such as booka, pixies, or similar faeries. Phaerim appear to be smaller than normal Elf-like folk, except that they have a pair of wings resembling those of dragonflies or sometimes butterflies. For unknown reasons, there are at least twice as many Phaerim females as there are males. Phaerim stand no taller than the average Halfling (3’) but have a more slight build, seldom being heavier than 40 pounds.",
            "Restrictions": "Phaerim can be any class but generally gravitate to magical classes. If allowed by the GM, Phaerim will be more likely to pursue classes associated with nature than the standard fare. Thus Rangers and Druids are more common than Fighters and Clerics. Phaerim are required to have a minimum Dexterity score of 9. Phaerim are quite captivating, and must also have a minimum Charisma score of 11. Due to their very small stature, they may not have a Strength score higher than 15. Also size related, Phaerim roll hit dice one size smaller than normal; a d8 would become a d6, a d6 to d4, and a d4 would instead be d3 (d6, 1-2=1, 3-4=2, 5-6=3). Phaerim may not use Large weapons, and must wield Medium weapons with both hands.",
            "SpecialAbilities": "Phaerim normally walk like other races, but their most remarkable ability is limited flight while unencumbered (at double the normal movement rates). Phaerim can fly up to 10 rounds, but must remain grounded an equivalent amount of time after any flight. A lightly-encumbered Phaerim can fly up to 5 rounds but must rest for twice as many rounds as those flown (for instance, a lightly-encumbered flight of 4 rounds requires 8 rounds grounded). Phaerim take half-damage from falls due to their reduced weight and wings. Similar to Halflings, Phaerim are able to hide very effectively; so long as they remain still there is only a 10% chance they will be detected outdoors in forested environments. Even indoors, in dungeons, or in non-preferred terrain they are able to hide such that there is only a 30% chance of detection. Note that a Phaerim Thief will roll for hiding attempts only once, using either the Thief ability or the Phaerim ability, whichever is better.",
            "ThiefAbilityAdjustments": "",
            "SavingThrows": "Like Elves, Phaerim save at +1 vs. Paralysis or Petrify and +2 vs. Magic Wands and Spells.",
            "InitialLevels": ""
        }];
        return data;
    }

    getCoreRaces(){
        return this.getData().filter(function(obj) {
            return obj.Core === 1;
        });
    }

    getAllRaceNames(){
        return this.getData().map(function(obj) {
            return obj.Name;
        });
    }

    getCoreRaceNames(){
        return this.getCoreRaces().map((obj) => {
            return obj.Name;
        });
    }

    getRaceByName(raceName){
        return this.getData().filter(function (obj) {
            return obj.Name.toLowerCase() === raceName.toLowerCase();
        })[0];
    }
}

module.exports = RacesData;
